### ISSUE TITLE
New implementation of PES learning rule

### ISSUE THREAD

**Issue by bmorcos** [nengo-labs/nengo-ocl#131]
I created the `SimPES` operator class in `nengo` which will need to be implemented here. See [#1254](https://github.com/nengo/nengo/pull/1254) in `nengo`

**Comment by bmorcos** [comment]
I would be interested in taking a stab at this and learning how `nengo_ocl` works, but just reading through the code is proving difficult. @hunse, maybe when you have some time you can point me in the right direction.

**Comment by hunse** [comment]
I sent @bmorcos some information via email. Then I realized it wouldn't hurt to have it here, in case it can help others figure out what's going on in this project. It's the kind of thing that I'd like to expand at some point to have a good description of the whole project.

First, the important files:
- simulator.py: This is where the `nengo_ocl.Simulator` itself is. We use the Nengo builder to take the model and turn it into signals and operators. Then, we copy all the signals into OCL, and create OCL versions of all the operators. This is what the `Simulator.plan_*` functions do; each one of them is responsible for creating an OCL kernel (or kernels) to execute the corresponding operator.
- clra_nonlinearities.py: This is where the kernels for most operators are (i.e. most of the `Simulator.plan_*` functions call a `plan_*` function in here to generate the kernel). Each plan function follows roughly the same template: Do some checks on the arguments; Generate the C code for the kernel, using Mako to fill in variable things like datatypes; compile the C code as a PyOpenCL Program, and set the arguments; create and return a Plan object responsible for executing that cl.Program.
- clra_gemv.py: This contains kernels specific to the GEMV (matrix-vector multiply) operation, since it's such an important and specialized operation for us. You probably don't need to worry about it, though.
- clraggedarray.py: This contains the OCL implementation of RaggedArray, which you can essentially think of as a list of arrays. Whereas Numpy allows lists of arrays of the same size to be made into one big array (e.g. if you've got five 3x2 arrays, you can make a 5x3x2 array), there's no way to make arrays of different sizes into one big one. RaggedArray and CLRaggedArray do this, by making one big memory buffer where all the data is stored, and managing the reading and writing of that. Again, you shouldn't have to change anything in these files, but it's good to know what they're doing, since we use this data type all over the place.

For getting started on writing a PES kernel, you probably want to look at the BCM and Oja kernels in clra_nonlinearities.py. For each kernel, you'll see that there are a lot of arguments that go in. Essentially, they're all lists of different aspects of the input ragged arrays. When we're doing computations with ragged arrays, essentially we want to write kernels that can take in a list of arrays of different sizes, and perform the operation on each one of those arrays.

Let's take the BCM kernel as an example. It gets arguments shape0s and shape1s, these are lists of the `.shape[0]` and `.shape[1]` for each output. Then we have pre_stride0s and pre_starts, these give the strides along axis 0 and a pointer to where the data starts for each array in the `pre` ragged array. `pre_data` is the buffer itself. Then we have similar things for the `post` ragged array, followed by `theta` and `delta`. Finally, there's just a list of the alphas (learning rates) for all the different operators. So each of these lists will be of length N, where N is the number of SimPES operators that we've combined into this single kernel.

Then there's the kernel itself. It starts by getting ids, as is typical with OCL kernels. Here, `k` is the index of which array we're treating right now (0 <= k < N), so we use it to index into all of the input lists. `ij` tells the kernel which individual element to treat. I split it into `i` and `j` (row and column indices), and then this kernel computes element (i, j) of the output (`delta`).

**Comment by bmorcos** [comment]
I suppose we would also need to add the `apply-every` argument to the other learning rules as well. Unless we just ignore that assuming that OCL implementation should be fast enough already and there's no point adding this functionality?

**Comment by hunse** [comment]
Ideally, this simulator would support all functionality that the Nengo simulator does. So eventually we'd want to implement `apply_every`. But first worry about getting SimPES to work without `apply_every`, and then add it in for all the learning rules.
